komga:
  workspace: localdb
  database:
#     PostgreSQL settings for local development
     type: POSTGRES
     host: localhost
     port: 5432
     name: komga
     username: postgres
     password: password
     hikari:
       maximum-pool-size: 10
       minimum-idle: 2
       connection-timeout: 30000
       idle-timeout: 600000
       max-lifetime: 1800000

  lucene:
    data-directory: \${komga.config-dir}/lucene/\${komga.workspace}
