komga:
  workspace: localdb
  database:
    url: jdbc:postgresql://localhost:5433/komga_\${komga.workspace}
    username: komga
    password: komga_password
    driver-class-name: org.postgresql.Driver
  tasks-db:
    url: jdbc:postgresql://localhost:5433/komga_\${komga.workspace}_tasks
    username: komga
    password: komga_password
    driver-class-name: org.postgresql.Driver
  lucene:
    data-directory: \${komga.config-dir}/lucene/\${komga.workspace}
