name: Dispatch events (disabled for fork)

on:
  workflow_dispatch:

jobs:
  disabled:
    name: This workflow is disabled for this fork
    runs-on: ubuntu-latest
    steps:
    - run: echo "This workflow is disabled for this fork"
